//! Code generation for the `.apss/build/` crate.
//!
//! Generates a minimal Rust crate that statically links only the declared
//! standards, producing a project-local composed binary.

use crate::lockfile::Lockfile;
use crate::resolution::ResolvedProjectConfig;
use std::io::Write;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Errors from code generation.
#[derive(Debug, Error)]
pub enum CodegenError {
    /// Failed to write a generated file.
    #[error("failed to write {path}: {source}")]
    Io {
        path: String,
        source: std::io::Error,
    },

    /// A requested local package was not found in the provided repository.
    #[error("local package '{package}' not found under {repo}")]
    LocalPackageNotFound { package: String, repo: String },

    /// A registry dependency could not be emitted from an exact lockfile pin.
    #[error("standard '{standard}' is not exactly resolved in apss.lock")]
    UnresolvedRegistryPackage { standard: String },
}

/// Options controlling generated build crate dependency sources.
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// Local repository root to use for path dependencies instead of registry
    /// versions. Intended for pre-publish distribution testing.
    pub local_repo: Option<PathBuf>,
}

/// Generate the `.apss/build/` crate from a resolved config.
///
/// Creates:
/// - `.apss/build/Cargo.toml` with dependencies for each declared standard
/// - `.apss/build/src/main.rs` with register() calls and CLI dispatch
pub fn generate_build_crate(
    config: &ResolvedProjectConfig,
    lockfile: Option<&Lockfile>,
    output_dir: &Path,
) -> Result<Vec<String>, CodegenError> {
    generate_build_crate_with_options(config, lockfile, output_dir, &CodegenOptions::default())
}

/// Generate the `.apss/build/` crate with explicit codegen options.
pub fn generate_build_crate_with_options(
    config: &ResolvedProjectConfig,
    lockfile: Option<&Lockfile>,
    output_dir: &Path,
    options: &CodegenOptions,
) -> Result<Vec<String>, CodegenError> {
    let mut generated_files = Vec::new();

    // Create directories
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| CodegenError::Io {
        path: src_dir.display().to_string(),
        source: e,
    })?;

    // Generate Cargo.toml
    let cargo_path = output_dir.join("Cargo.toml");
    generate_cargo_toml(config, lockfile, &cargo_path, options)?;
    generated_files.push(cargo_path.display().to_string());

    // Generate main.rs
    let main_path = src_dir.join("main.rs");
    generate_main_rs(config, &main_path)?;
    generated_files.push(main_path.display().to_string());

    Ok(generated_files)
}

fn generate_cargo_toml(
    config: &ResolvedProjectConfig,
    lockfile: Option<&Lockfile>,
    path: &Path,
    options: &CodegenOptions,
) -> Result<(), CodegenError> {
    let mut content = String::new();

    content.push_str("# AUTO-GENERATED by `apss install`. Do not edit manually.\n\n");
    content.push_str("[package]\n");
    content.push_str("name = \"apss-local\"\n");
    content.push_str("version = \"0.0.0\"\n");
    content.push_str("edition = \"2024\"\n");
    content.push_str("publish = false\n\n");
    content.push_str("[[bin]]\n");
    content.push_str(&format!("name = \"{}\"\n", super::BIN_NAME));
    content.push_str("path = \"src/main.rs\"\n\n");
    content.push_str("[dependencies]\n");

    if let Some(local_repo) = &options.local_repo {
        let core_path = find_local_package_dir(local_repo, "apss-core")?;
        content.push_str(&format!(
            "apss-core = {{ path = \"{}\" }}\n",
            escape_toml_path(&core_path)
        ));
    } else {
        // Use pinned core version from lockfile, or fall back to current version
        let core_version = lockfile
            .map(|l| l.core.version.as_str())
            .unwrap_or(env!("CARGO_PKG_VERSION"));
        content.push_str(&format!("apss-core = {{ version = \"{core_version}\" }}\n"));
    }

    for standard in config.standards.values() {
        if !standard.enabled {
            continue;
        }
        if let Some(local_repo) = &options.local_repo {
            let package_path = find_local_package_dir(local_repo, &standard.crate_name)?;
            let ident = standard_crate_ident(&standard.crate_name);
            content.push_str(&format!(
                "{ident} = {{ package = \"{}\", path = \"{}\" }}\n",
                standard.crate_name,
                escape_toml_path(&package_path)
            ));
        } else {
            // Registry installs must use exact pins from apss.lock. Local
            // pre-publish testing should use --local-repo instead of masking
            // unresolved registry state with version ranges.
            let version = lockfile
                .and_then(|l| l.find_package(&standard.id))
                .map(|p| p.version.as_str())
                .filter(|version| !version.starts_with("UNRESOLVED("))
                .ok_or_else(|| CodegenError::UnresolvedRegistryPackage {
                    standard: standard.id.clone(),
                })?;
            let ident = standard_crate_ident(&standard.crate_name);
            // Substandard selection (APSS.yaml `substandards`) maps to cargo
            // features of the parent standard crate (ADR-0002 / DI01: substandards
            // ship as feature modules, not separate crates). None means "all
            // substandards", which is cargo's default feature set, so we emit no
            // override. Some(list) restricts the build to the mapped features.
            match feature_selection(standard) {
                Some(features) => {
                    let rendered = features
                        .iter()
                        .map(|feature| format!("\"{feature}\""))
                        .collect::<Vec<_>>()
                        .join(", ");
                    content.push_str(&format!(
                        "{ident} = {{ package = \"{}\", version = \"{version}\", default-features = false, features = [{rendered}] }}\n",
                        standard.crate_name
                    ));
                }
                None => {
                    content.push_str(&format!(
                        "{ident} = {{ package = \"{}\", version = \"{version}\" }}\n",
                        standard.crate_name
                    ));
                }
            }
        }
    }

    let mut file = std::fs::File::create(path).map_err(|e| CodegenError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    file.write_all(content.as_bytes())
        .map_err(|e| CodegenError::Io {
            path: path.display().to_string(),
            source: e,
        })?;

    Ok(())
}

fn find_local_package_dir(repo: &Path, package_name: &str) -> Result<PathBuf, CodegenError> {
    let canonical_repo = repo.canonicalize().map_err(|e| CodegenError::Io {
        path: repo.display().to_string(),
        source: e,
    })?;
    find_local_package_dir_inner(&canonical_repo, package_name)?.ok_or_else(|| {
        CodegenError::LocalPackageNotFound {
            package: package_name.to_string(),
            repo: canonical_repo.display().to_string(),
        }
    })
}

fn find_local_package_dir_inner(
    dir: &Path,
    package_name: &str,
) -> Result<Option<PathBuf>, CodegenError> {
    let cargo_toml = dir.join("Cargo.toml");
    if cargo_toml.is_file() {
        let content = std::fs::read_to_string(&cargo_toml).map_err(|e| CodegenError::Io {
            path: cargo_toml.display().to_string(),
            source: e,
        })?;
        if package_name_from_manifest(&content).as_deref() == Some(package_name) {
            return Ok(Some(dir.to_path_buf()));
        }
    }

    let entries = std::fs::read_dir(dir).map_err(|e| CodegenError::Io {
        path: dir.display().to_string(),
        source: e,
    })?;
    for entry in entries {
        let entry = entry.map_err(|e| CodegenError::Io {
            path: dir.display().to_string(),
            source: e,
        })?;
        let path = entry.path();
        if !path.is_dir() || should_skip_dir(&path) {
            continue;
        }
        if let Some(found) = find_local_package_dir_inner(&path, package_name)? {
            return Ok(Some(found));
        }
    }

    Ok(None)
}

fn package_name_from_manifest(content: &str) -> Option<String> {
    let manifest: toml::Value = toml::from_str(content).ok()?;
    manifest
        .get("package")?
        .get("name")?
        .as_str()
        .map(ToOwned::to_owned)
}

fn standard_crate_ident(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Resolve the cargo features a standard's build crate should enable from its
/// selected substandards.
///
/// This is fully generic: it holds no standard-specific knowledge and performs
/// no mapping. Each substandard profile code IS the cargo feature name (ADR-0002
/// / DI01: the feature key equals the substandard code, enforced by the parity
/// validator). `None` means no `features`/`default-features` override is emitted,
/// so cargo uses the crate's default feature set (all substandards). `Some(list)`
/// is passed through verbatim; the caller then emits
/// `default-features = false, features = [...]`.
fn feature_selection(standard: &crate::resolution::ResolvedStandard) -> Option<Vec<String>> {
    standard.substandards.as_ref().cloned()
}

fn should_skip_dir(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    matches!(
        name,
        ".git" | ".apss" | "target" | "node_modules" | ".cargo"
    )
}

fn escape_toml_path(path: &Path) -> String {
    path.display().to_string().replace('\\', "\\\\")
}

fn generate_main_rs(config: &ResolvedProjectConfig, path: &Path) -> Result<(), CodegenError> {
    let mut content = String::new();

    content.push_str("// AUTO-GENERATED by `apss install`. Do not edit manually.\n\n");
    content.push_str("use apss_core::config::{self, CONFIG_FILENAME};\n");
    content.push_str("use apss_core::registry::ProjectRunner;\n\n");
    content.push_str("fn main() {\n");
    content.push_str("    let cwd = match std::env::current_dir() {\n");
    content.push_str("        Ok(path) => path,\n");
    content.push_str("        Err(error) => {\n");
    content.push_str("            eprintln!(\"failed to get current directory: {error}\");\n");
    content.push_str("            std::process::exit(1);\n");
    content.push_str("        }\n");
    content.push_str("    };\n");
    content.push_str("    let config_path = config::find_project_config(&cwd)\n");
    content.push_str("        .unwrap_or_else(|| std::path::PathBuf::from(CONFIG_FILENAME));\n");
    content.push_str("    let mut runner = ProjectRunner::from_config_file(&config_path)\n");
    content.push_str("        .unwrap_or_else(|error| {\n");
    content.push_str("            eprintln!(\"failed to load {CONFIG_FILENAME}: {error}\");\n");
    content.push_str("            std::process::exit(1);\n");
    content.push_str("        });\n\n");

    for standard in config.standards.values() {
        if !standard.enabled {
            continue;
        }
        let ident = standard_crate_ident(&standard.crate_name);
        content.push_str(&format!("    {ident}::register(&mut runner);\n"));
    }

    content.push_str("\n    let args: Vec<String> = std::env::args().skip(1).collect();\n");
    content.push_str("    std::process::exit(runner.run(&args));\n");
    content.push_str("}\n");

    let mut file = std::fs::File::create(path).map_err(|e| CodegenError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    file.write_all(content.as_bytes())
        .map_err(|e| CodegenError::Io {
            path: path.display().to_string(),
            source: e,
        })?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ProjectInfo, ToolConfig};
    use crate::resolution::ResolvedStandard;
    use std::collections::BTreeMap;

    fn test_config() -> ResolvedProjectConfig {
        ResolvedProjectConfig {
            project: ProjectInfo {
                name: "test-project".to_string(),
                apss_version: "v1".to_string(),
            },
            standards: BTreeMap::from([
                (
                    "code-topology".to_string(),
                    ResolvedStandard {
                        id: "APS-V1-0001".to_string(),
                        slug: "code-topology".to_string(),
                        version_req: ">=1.0.0".to_string(),
                        enabled: true,
                        substandards: None,
                        config: toml::Value::Table(Default::default()),
                        crate_name: "apss-v1-0001-code-topology".to_string(),
                    },
                ),
                (
                    "fitness".to_string(),
                    ResolvedStandard {
                        id: "APS-V1-0003".to_string(),
                        slug: "fitness".to_string(),
                        version_req: ">=1.0.0".to_string(),
                        enabled: true,
                        substandards: None,
                        config: toml::Value::Table(Default::default()),
                        crate_name: "apss-v1-0003-fitness-functions".to_string(),
                    },
                ),
            ]),
            tool: ToolConfig::default(),
            source_files: vec![],
        }
    }

    fn test_lockfile() -> Lockfile {
        let mut lockfile = Lockfile::new("1.0.0".to_string());
        lockfile.packages.push(crate::lockfile::LockedPackage {
            id: "APS-V1-0001".to_string(),
            slug: "code-topology".to_string(),
            crate_name: "apss-v1-0001-code-topology".to_string(),
            version: "1.0.0".to_string(),
            checksum: "sha256:test".to_string(),
            source: "registry+https://crates.io".to_string(),
            substandards: vec![],
        });
        lockfile.packages.push(crate::lockfile::LockedPackage {
            id: "APS-V1-0003".to_string(),
            slug: "fitness".to_string(),
            crate_name: "apss-v1-0003-fitness-functions".to_string(),
            version: "1.0.0".to_string(),
            checksum: "sha256:test".to_string(),
            source: "registry+https://crates.io".to_string(),
            substandards: vec![],
        });
        lockfile
    }

    #[test]
    fn test_generate_build_crate() {
        let temp = tempfile::tempdir().unwrap();
        let config = test_config();

        let lockfile = test_lockfile();

        let files = generate_build_crate(&config, Some(&lockfile), temp.path()).unwrap();
        assert_eq!(files.len(), 2);

        // Verify Cargo.toml
        let cargo = std::fs::read_to_string(temp.path().join("Cargo.toml")).unwrap();
        assert!(cargo.contains("apss-v1-0001-code-topology"));
        assert!(cargo.contains("apss-v1-0003-fitness-functions"));
        assert!(
            cargo.contains(
                "apss_v1_0001_code_topology = { package = \"apss-v1-0001-code-topology\""
            )
        );
        assert!(cargo.contains("apss-core"));
        assert!(cargo.contains("publish = false"));

        // Verify main.rs
        let main = std::fs::read_to_string(temp.path().join("src/main.rs")).unwrap();
        assert!(main.contains("apss_v1_0001_code_topology::register"));
        assert!(main.contains("apss_v1_0003_fitness_functions::register"));
        assert!(main.contains("config::find_project_config"));
        assert!(main.contains("ProjectRunner::from_config_file"));
    }

    #[test]
    fn test_generate_skips_disabled() {
        let temp = tempfile::tempdir().unwrap();
        let mut config = test_config();
        config.standards.get_mut("fitness").unwrap().enabled = false;

        let lockfile = test_lockfile();

        generate_build_crate(&config, Some(&lockfile), temp.path()).unwrap();

        let cargo = std::fs::read_to_string(temp.path().join("Cargo.toml")).unwrap();
        assert!(cargo.contains("apss-v1-0001-code-topology"));
        assert!(!cargo.contains("apss-v1-0003-fitness-functions"));

        let main = std::fs::read_to_string(temp.path().join("src/main.rs")).unwrap();
        assert!(main.contains("apss_v1_0001_code_topology::register"));
        assert!(!main.contains("apss_v1_0003_fitness_functions::register"));
    }

    #[test]
    fn test_registry_codegen_rejects_unresolved_lockfile() {
        let temp = tempfile::tempdir().unwrap();
        let config = test_config();

        let err = generate_build_crate(&config, None, temp.path()).unwrap_err();
        assert!(matches!(
            err,
            CodegenError::UnresolvedRegistryPackage { .. }
        ));
    }

    #[test]
    fn test_substandard_selection_emits_features() {
        let temp = tempfile::tempdir().unwrap();
        let mut config = test_config();
        // Drop the second standard so the assertion targets code-topology.
        config.standards.remove("fitness");
        config
            .standards
            .get_mut("code-topology")
            .unwrap()
            .substandards = Some(vec!["RS01".to_string(), "FD01".to_string()]);

        generate_build_crate(&config, Some(&test_lockfile()), temp.path()).unwrap();

        let cargo = std::fs::read_to_string(temp.path().join("Cargo.toml")).unwrap();
        // Substandard codes pass through verbatim as cargo feature names.
        assert!(cargo.contains(
            "apss_v1_0001_code_topology = { package = \"apss-v1-0001-code-topology\", version = \"1.0.0\", default-features = false, features = [\"RS01\", \"FD01\"] }"
        ));
    }

    #[test]
    fn test_no_substandard_selection_emits_no_features_override() {
        let temp = tempfile::tempdir().unwrap();
        let mut config = test_config();
        config.standards.remove("fitness");
        // substandards is None by default in test_config().

        generate_build_crate(&config, Some(&test_lockfile()), temp.path()).unwrap();

        let cargo = std::fs::read_to_string(temp.path().join("Cargo.toml")).unwrap();
        assert!(cargo.contains(
            "apss_v1_0001_code_topology = { package = \"apss-v1-0001-code-topology\", version = \"1.0.0\" }"
        ));
        assert!(!cargo.contains("default-features = false"));
        assert!(!cargo.contains("features = ["));
    }

    #[test]
    fn test_generate_with_local_repo_paths() {
        let temp = tempfile::tempdir().unwrap();
        let repo = temp.path().join("repo");
        let output = temp.path().join("out");
        std::fs::create_dir_all(repo.join("crates/apss-core")).unwrap();
        std::fs::create_dir_all(repo.join("standards/code-topology")).unwrap();
        std::fs::create_dir_all(repo.join("standards/fitness")).unwrap();
        std::fs::write(
            repo.join("crates/apss-core/Cargo.toml"),
            "[package]\nname = \"apss-core\"\n",
        )
        .unwrap();
        std::fs::write(
            repo.join("standards/code-topology/Cargo.toml"),
            "[package]\nname = \"apss-v1-0001-code-topology\"\n",
        )
        .unwrap();
        std::fs::write(
            repo.join("standards/fitness/Cargo.toml"),
            "[package]\nname = \"apss-v1-0003-fitness-functions\"\n",
        )
        .unwrap();

        generate_build_crate_with_options(
            &test_config(),
            None,
            &output,
            &CodegenOptions {
                local_repo: Some(repo.clone()),
            },
        )
        .unwrap();

        let cargo = std::fs::read_to_string(output.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("apss-core = { path = "));
        assert!(cargo.contains(
            "apss_v1_0001_code_topology = { package = \"apss-v1-0001-code-topology\", path = "
        ));
        assert!(cargo.contains(
            "apss_v1_0003_fitness_functions = { package = \"apss-v1-0003-fitness-functions\", path = "
        ));
        assert!(!cargo.contains("version = \">=1.0.0\""));
    }
}
